---
name: render_config
pack: default
description: Render the configuration
runner_type: python-script
entry_point: "render_config.py"
enabled: true
parameters:
    j2_location:
        type: string
        description: Location of the Jinja2 file
        default: ~/automation/cloned_content/templates
        required: true
        position: 1
    variables:
        type: object
        description: List of the variables
        required: true
        position: 1
    function:
        type: string
        description: Used to identify the filename based on the config
        required: true
        position: 2
    device_id:
        type: string
        description: Used to identify the filename based on the device
        required: true
        position: 3